// src/pages/Profile.jsx
import React, { useState, useEffect } from 'react';
import { User, Order, WishlistItem } from '../api/entities';

const TIER_CONFIG = {
  Citizen: { color: 'text-white/60', bg: 'bg-white/10', points: 0 },
  Gold: { color: 'text-[#C5A059]', bg: 'bg-[#C5A059]/20', points: 500 },
  Platinum: { color: 'text-gray-300', bg: 'bg-gray-500/20', points: 2000 },
  'Diamond Elite': { color: 'text-blue-300', bg: 'bg-blue-500/20', points: 5000 },
};

export default function Profile() {
  const [user, setUser] = useState(null);
  const [orders, setOrders] = useState([]);
  const [wishlist, setWishlist] = useState([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState('overview');
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({});

  useEffect(() => {
    Promise.all([
      User.me(),
      Order.list(),
      WishlistItem.list(),
    ]).then(([u, o, w]) => {
      setUser(u);
      setForm({ bio: u?.bio || '', phone: u?.phone || '', preferred_language: u?.preferred_language || 'en' });
      setOrders(o);
      setWishlist(w);
    }).finally(() => setLoading(false));
  }, []);

  const saveProfile = async () => {
    try {
      await User.updateMe(form);
      setUser(u => ({ ...u, ...form }));
      setEditing(false);
    } catch (e) {
      alert('Failed to update profile');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#050505] flex items-center justify-center">
        <div className="text-[#C5A059] animate-pulse font-serif text-2xl">Loading profile...</div>
      </div>
    );
  }

  const tier = user?.status_tier || 'Citizen';
  const tierConfig = TIER_CONFIG[tier] || TIER_CONFIG.Citizen;
  const points = user?.loyalty_points || 0;

  return (
    <div className="min-h-screen bg-[#050505]">
      {/* Profile Header — 38% */}
      <div className="relative pt-16 pb-24 px-6 md:px-16 overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0 bg-gradient-to-br from-[#C5A059]/20 to-transparent" />
        </div>
        <div className="max-w-7xl mx-auto relative">
          <div className="flex flex-col md:flex-row items-start md:items-end gap-8">
            {/* Avatar */}
            <div className="relative">
              <div className="w-28 h-28 bg-[#C5A059]/20 border-2 border-[#C5A059]/30 flex items-center justify-center text-4xl">
                {user?.avatar_url ? (
                  <img src={user.avatar_url} alt="" className="w-full h-full object-cover" />
                ) : (
                  <span className="text-[#C5A059] font-serif text-3xl">
                    {user?.full_name?.[0] || user?.email?.[0] || 'U'}
                  </span>
                )}
              </div>
              <div className={`absolute -bottom-2 -right-2 ${tierConfig.bg} ${tierConfig.color} text-[9px] uppercase tracking-[0.2em] px-2 py-1 border border-current/30`}>
                {tier}
              </div>
            </div>

            {/* Info */}
            <div className="flex-1">
              <h1 className="text-3xl md:text-4xl font-serif text-white font-light mb-2">
                {user?.full_name || 'Sovereign Member'}
              </h1>
              <div className="text-white/40 text-sm mb-4">{user?.email}</div>

              {/* Stats */}
              <div className="flex gap-8">
                {[
                  { label: 'Points', value: points.toLocaleString() },
                  { label: 'Orders', value: orders.length },
                  { label: 'Wishlist', value: wishlist.length },
                ].map(stat => (
                  <div key={stat.label}>
                    <div className="text-2xl font-serif text-[#C5A059]">{stat.value}</div>
                    <div className="text-white/40 text-xs uppercase tracking-[0.2em]">{stat.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Loyalty Progress */}
            <div className="w-full md:w-64">
              <div className="text-white/40 text-xs uppercase tracking-[0.2em] mb-2">Loyalty Status</div>
              <div className={`${tierConfig.color} font-serif text-lg mb-2`}>{tier}</div>
              <div className="h-1 bg-white/10">
                <div
                  className="h-full bg-[#C5A059] transition-all"
                  style={{ width: `${Math.min(100, (points / (tierConfig.points || 5000)) * 100)}%` }}
                />
              </div>
              <div className="text-white/30 text-xs mt-1">{points} / {tierConfig.points || 5000} pts</div>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="border-t border-white/5 px-6 md:px-16">
        <div className="max-w-7xl mx-auto flex gap-8">
          {[
            { id: 'overview', label: 'Overview' },
            { id: 'orders', label: `Purchases (${orders.length})` },
            { id: 'wishlist', label: `Saved (${wishlist.length})` },
            { id: 'settings', label: 'Settings' },
          ].map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`py-4 text-xs uppercase tracking-[0.3em] border-b-2 transition-all whitespace-nowrap ${
                tab === t.id ? 'border-[#C5A059] text-[#C5A059]' : 'border-transparent text-white/40 hover:text-white'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {/* Content — 62% */}
      <div className="max-w-7xl mx-auto px-6 md:px-16 py-12">
        {tab === 'overview' && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="md:col-span-2 space-y-4">
              <h2 className="text-white/40 text-xs uppercase tracking-[0.3em] mb-6">Recent Orders</h2>
              {orders.slice(0, 3).map(order => (
                <div key={order.id} className="border border-white/10 p-4 flex items-center justify-between">
                  <div>
                    <div className="text-white text-sm font-light mb-1">
                      {order.items?.map(i => i.name).join(', ').slice(0, 50) || 'Order'}...
                    </div>
                    <div className="text-white/30 text-xs">₦{order.total_amount?.toLocaleString()}</div>
                  </div>
                  <div className={`text-xs uppercase tracking-[0.2em] px-3 py-1 ${
                    order.status === 'delivered' ? 'text-green-400 bg-green-400/10' :
                    order.status === 'shipped' ? 'text-blue-400 bg-blue-400/10' :
                    'text-[#C5A059] bg-[#C5A059]/10'
                  }`}>
                    {order.status}
                  </div>
                </div>
              ))}
              {orders.length === 0 && (
                <p className="text-white/20 text-sm">No orders yet. Start shopping to build your collection.</p>
              )}
            </div>

            {/* Rewards */}
            <div className="border border-[#C5A059]/20 p-6 bg-[#C5A059]/5">
              <div className="text-[#C5A059] text-xs uppercase tracking-[0.3em] mb-4">Rewards</div>
              <div className="text-4xl font-serif text-white mb-1">{points.toLocaleString()}</div>
              <div className="text-white/40 text-xs mb-6">Loyalty Points</div>
              <div className="space-y-3">
                {[
                  { pts: 100, reward: 'Free shipping' },
                  { pts: 500, reward: 'Gold membership' },
                  { pts: 1000, reward: 'Exclusive drop access' },
                ].map(r => (
                  <div key={r.pts} className={`flex items-center gap-3 text-xs ${points >= r.pts ? 'text-[#C5A059]' : 'text-white/30'}`}>
                    <span>{points >= r.pts ? '✓' : '○'}</span>
                    <span>{r.reward}</span>
                    <span className="ml-auto">{r.pts} pts</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {tab === 'orders' && (
          <div className="space-y-4">
            {orders.length === 0 ? (
              <p className="text-white/30 font-serif text-xl text-center py-12">No orders yet</p>
            ) : orders.map(order => (
              <div key={order.id} className="border border-white/10 p-6">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <div className="text-white/30 text-xs uppercase tracking-[0.2em] mb-1">
                      {new Date(order.created_date).toLocaleDateString('en-NG', { year: 'numeric', month: 'long', day: 'numeric' })}
                    </div>
                    <div className="text-white font-serif text-lg">₦{order.total_amount?.toLocaleString()}</div>
                  </div>
                  <div className={`text-xs uppercase tracking-[0.2em] px-3 py-1 ${
                    order.status === 'delivered' ? 'text-green-400 bg-green-400/10' :
                    order.status === 'shipped' ? 'text-blue-400 bg-blue-400/10' :
                    order.status === 'cancelled' ? 'text-red-400/60 bg-red-400/10' :
                    'text-[#C5A059] bg-[#C5A059]/10'
                  }`}>
                    {order.status}
                  </div>
                </div>
                {order.items?.map((item, i) => (
                  <div key={i} className="flex items-center gap-4 py-3 border-t border-white/5">
                    {item.image && (
                      <img src={item.image} alt={item.name} className="w-16 h-16 object-cover" />
                    )}
                    <div>
                      <div className="text-white text-sm">{item.name}</div>
                      {item.size && <div className="text-white/40 text-xs">Size: {item.size}</div>}
                      <div className="text-[#C5A059] text-sm">₦{(item.price * item.quantity).toLocaleString()}</div>
                    </div>
                  </div>
                ))}
                {order.tracking_number && (
                  <div className="mt-4 pt-4 border-t border-white/10 text-xs">
                    <span className="text-white/30 uppercase tracking-[0.2em]">Tracking: </span>
                    <span className="text-[#C5A059]">{order.tracking_number}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {tab === 'wishlist' && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {wishlist.length === 0 ? (
              <div className="col-span-4 text-center py-12">
                <p className="text-white/30 font-serif text-xl">No saved items</p>
              </div>
            ) : wishlist.map(item => (
              <div key={item.id} className="group">
                <div className="aspect-[3/4] overflow-hidden mb-3 bg-[#0E0E0E]">
                  {item.product_image ? (
                    <img src={item.product_image} alt={item.product_name} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                  ) : (
                    <div className="w-full h-full bg-white/5" />
                  )}
                </div>
                <div className="text-white text-sm font-light">{item.product_name}</div>
                <div className="text-[#C5A059] text-sm">₦{item.product_price?.toLocaleString()}</div>
              </div>
            ))}
          </div>
        )}

        {tab === 'settings' && (
          <div className="max-w-lg">
            <h2 className="text-white font-serif text-2xl font-light mb-8">Profile Settings</h2>
            <div className="space-y-6">
              <div>
                <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Bio</label>
                {editing ? (
                  <textarea
                    value={form.bio}
                    onChange={e => setForm(f => ({ ...f, bio: e.target.value }))}
                    className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] resize-none"
                    rows={3}
                  />
                ) : (
                  <p className="text-white/60 text-sm">{user?.bio || 'No bio set'}</p>
                )}
              </div>
              <div>
                <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Phone</label>
                {editing ? (
                  <input
                    type="tel"
                    value={form.phone}
                    onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}
                    className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059]"
                  />
                ) : (
                  <p className="text-white/60 text-sm">{user?.phone || 'Not set'}</p>
                )}
              </div>
              <div>
                <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Preferred Language</label>
                {editing ? (
                  <select
                    value={form.preferred_language}
                    onChange={e => setForm(f => ({ ...f, preferred_language: e.target.value }))}
                    className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059]"
                  >
                    {[['en','English'],['ha','Hausa'],['yo','Yoruba'],['ig','Igbo'],['fr','Français'],['ar','العربية']].map(([v,l]) => (
                      <option key={v} value={v}>{l}</option>
                    ))}
                  </select>
                ) : (
                  <p className="text-white/60 text-sm capitalize">{form.preferred_language || 'English'}</p>
                )}
              </div>
              <div className="flex gap-3 pt-4">
                {editing ? (
                  <>
                    <button onClick={saveProfile} className="bg-[#C5A059] text-black px-6 py-3 text-xs uppercase tracking-[0.2em] font-bold hover:bg-white transition-colors">
                      Save Changes
                    </button>
                    <button onClick={() => setEditing(false)} className="border border-white/20 text-white/50 px-6 py-3 text-xs uppercase tracking-[0.2em] hover:border-white/50 transition-colors">
                      Cancel
                    </button>
                  </>
                ) : (
                  <button onClick={() => setEditing(true)} className="border border-[#C5A059]/30 text-[#C5A059] px-6 py-3 text-xs uppercase tracking-[0.2em] hover:bg-[#C5A059] hover:text-black transition-all">
                    Edit Profile
                  </button>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// src/routes/profile/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { fly, fade } from 'svelte/transition';
  import { supabase } from '$lib/supabase';
  import { currentUser, userProfile, auth, isAuthenticated } from '$lib/stores/auth';

  let orders: any[] = [];
  let wishlist: any[] = [];
  let xpEvents: any[] = [];
  let loading = true;
  let activeTab: 'overview' | 'orders' | 'wishlist' | 'rewards' = 'overview';
  let editMode = false;
  let editName = '';
  let savingProfile = false;

  const TIER_CONFIG: Record<string, any> = {
    citizen:  { color: '#FFFFFF', label: 'Citizen',      next: 'Patron',       nextXP: 500,   bg: 'from-white/10 to-transparent' },
    patron:   { color: '#F59E0B', label: 'Patron',       next: 'Curator',      nextXP: 2000,  bg: 'from-amber-800/30 to-transparent' },
    curator:  { color: '#C5A059', label: 'Curator',      next: 'Vanguard',     nextXP: 7500,  bg: 'from-hd-gold/20 to-transparent' },
    vanguard: { color: '#A855F7', label: 'Vanguard',     next: 'Daraja Elite', nextXP: 25000, bg: 'from-purple-800/30 to-transparent' },
    elite:    { color: '#C5A059', label: 'Daraja Elite', next: '—',            nextXP: 99999, bg: 'from-hd-gold/30 to-transparent' },
  };

  onMount(async () => {
    if (!$isAuthenticated) { goto('/auth?redirect=/profile'); return; }
    editName = $userProfile?.display_name ?? '';
    const uid = $currentUser!.id;

    const [{ data: ord }, { data: wish }, { data: xp }] = await Promise.all([
      supabase.from('orders').select('*').eq('user_id', uid).order('created_at', { ascending: false }).limit(10),
      supabase.from('wishlist').select('*,products(name,price,images)').eq('user_id', uid).limit(12),
      supabase.from('xp_events').select('*').eq('user_id', uid).order('created_at', { ascending: false }).limit(20),
    ]);

    orders   = ord   ?? [];
    wishlist = wish  ?? [];
    xpEvents = xp    ?? [];
    loading  = false;
  });

  $: tier = $userProfile?.prestige_tier ?? 'citizen';
  $: tierCfg = TIER_CONFIG[tier];
  $: xpProgress = $userProfile ? Math.min(($userProfile.xp / tierCfg.nextXP) * 100, 100) : 0;

  async function saveProfile() {
    if (!$currentUser) return;
    savingProfile = true;
    await supabase.from('profiles').update({ display_name: editName }).eq('user_id', $currentUser.id);
    savingProfile = false;
    editMode = false;
  }

  async function signOut() {
    await auth.signOut();
    goto('/');
  }

  const STATUS_MAP: Record<string, {label:string, color:string}> = {
    pending:   { label: 'Pending',   color: 'text-white/40' },
    confirmed: { label: 'Confirmed', color: 'text-blue-400' },
    shipped:   { label: 'Shipped',   color: 'text-yellow-400' },
    delivered: { label: 'Delivered', color: 'text-green-400' },
    cancelled: { label: 'Cancelled', color: 'text-red-400' },
  };
</script>

<svelte:head><title>Profile — House of Daraja</title></svelte:head>

<div class="min-h-screen bg-[#050505] pt-16 pb-28">
  {#if loading}
    <div class="flex items-center justify-center min-h-[80vh]">
      <div class="flex gap-2">
        {#each [0,1,2] as i}
          <div class="w-2 h-2 bg-hd-gold rounded-full animate-bounce" style="animation-delay:{i*150}ms"></div>
        {/each}
      </div>
    </div>
  {:else if $userProfile || $currentUser}
    <!-- Profile hero card -->
    <div class="relative bg-gradient-to-b {tierCfg.bg} border-b border-white/[0.04] pt-8 pb-0" in:fade>
      <div class="max-w-2xl mx-auto px-4 pb-6">
        <div class="flex items-start gap-5">
          <!-- Avatar -->
          <div class="relative shrink-0">
            {#if $userProfile?.avatar_url}
              <img src={$userProfile.avatar_url} alt="Avatar" class="w-20 h-20 rounded-full object-cover border-2" style="border-color: {tierCfg.color}" />
            {:else}
              <div class="w-20 h-20 rounded-full border-2 flex items-center justify-center bg-white/5" style="border-color: {tierCfg.color}">
                <span class="font-serif text-2xl" style="color: {tierCfg.color}">
                  {($userProfile?.display_name ?? $currentUser?.email ?? 'U').charAt(0).toUpperCase()}
                </span>
              </div>
            {/if}
            <div class="absolute -bottom-1 -right-1 w-4 h-4 bg-green-400 rounded-full border-2 border-[#050505]"></div>
          </div>

          <!-- Info -->
          <div class="flex-1 min-w-0">
            {#if editMode}
              <div class="flex gap-2 items-center">
                <input bind:value={editName} class="bg-white/[0.06] border border-hd-gold/30 text-white px-3 py-1.5 text-sm focus:outline-none flex-1" />
                <button on:click={saveProfile} disabled={savingProfile} class="bg-hd-gold text-black mono text-[8px] uppercase px-3 py-1.5 font-bold hover:bg-hd-gold/90">Save</button>
                <button on:click={() => editMode = false} class="text-white/30 text-xs hover:text-white/60">✕</button>
              </div>
            {:else}
              <div class="flex items-center gap-2">
                <h1 class="font-serif text-2xl text-white truncate">{$userProfile?.display_name ?? $currentUser?.email?.split('@')[0] ?? 'Member'}</h1>
                <button on:click={() => { editMode = true; editName = $userProfile?.display_name ?? ''; }} class="text-white/20 hover:text-hd-gold transition-colors">
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.5"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" /></svg>
                </button>
              </div>
            {/if}
            <div class="flex items-center gap-2 mt-1.5">
              <span class="mono text-[9px] uppercase tracking-widest px-2 py-0.5 border" style="color:{tierCfg.color}; border-color:{tierCfg.color}30">
                {tierCfg.label}
              </span>
              <span class="text-white/30 text-xs">·</span>
              <span class="mono text-[9px] text-white/40">{($currentUser?.email ?? '')}</span>
            </div>

            <!-- XP bar -->
            <div class="mt-3">
              <div class="flex justify-between mb-1">
                <span class="mono text-[8px] text-white/30 uppercase">XP Progress → {tierCfg.next}</span>
                <span class="mono text-[8px] text-hd-gold/60">{$userProfile?.xp ?? 0} / {tierCfg.nextXP}</span>
              </div>
              <div class="h-1 bg-white/[0.06] overflow-hidden">
                <div class="h-full bg-gradient-to-r from-hd-gold to-hd-gold/60 transition-all duration-1000" style="width:{xpProgress}%"></div>
              </div>
            </div>
          </div>
        </div>

        <!-- Stats row -->
        <div class="grid grid-cols-4 gap-3 mt-6 py-4 border-y border-white/[0.05]">
          {#each [[orders.length, 'Orders'],[wishlist.length, 'Saved'],[$userProfile?.xp ?? 0, 'XP'],[$userProfile?.lee_balance ?? 0, 'LEE']] as [val, label]}
            <div class="text-center">
              <div class="font-serif text-xl text-hd-gold">{val}</div>
              <div class="mono text-[8px] uppercase text-white/30 tracking-wider mt-0.5">{label}</div>
            </div>
          {/each}
        </div>
      </div>

      <!-- Tab nav -->
      <div class="max-w-2xl mx-auto px-4">
        <div class="flex border-b border-white/[0.06]">
          {#each [['overview','Overview'],['orders','My Orders'],['wishlist','Saved Items'],['rewards','Rewards']] as [tab, label]}
            <button
              on:click={() => activeTab = tab}
              class="flex-1 py-3 mono text-[9px] uppercase tracking-widest border-b-2 transition-all {activeTab === tab ? 'border-hd-gold text-hd-gold' : 'border-transparent text-white/30 hover:text-white/50'}"
            >{label}</button>
          {/each}
        </div>
      </div>
    </div>

    <!-- Tab content -->
    <div class="max-w-2xl mx-auto px-4 pt-6">

      {#if activeTab === 'overview'}
        <div class="space-y-4" in:fly={{ y: 10, duration: 300 }}>
          <div class="grid grid-cols-2 gap-4">
            <a href="/atelier" class="bg-white/[0.02] border border-white/[0.06] p-5 hover:border-hd-gold/20 transition-all group">
              <div class="text-2xl mb-3">✦</div>
              <p class="text-white font-light text-sm">Bespoke Atelier</p>
              <p class="text-white/30 text-xs mt-1">Commission a piece</p>
              <span class="mono text-[8px] text-hd-gold/50 group-hover:text-hd-gold transition-colors mt-3 block uppercase tracking-wider">→ Open Atelier</span>
            </a>
            <a href="/auction" class="bg-white/[0.02] border border-white/[0.06] p-5 hover:border-hd-gold/20 transition-all group">
              <div class="text-2xl mb-3">⚡</div>
              <p class="text-white font-light text-sm">Live Auction</p>
              <p class="text-white/30 text-xs mt-1">Bid on rare pieces</p>
              <span class="mono text-[8px] text-hd-gold/50 group-hover:text-hd-gold transition-colors mt-3 block uppercase tracking-wider">→ Enter Hall</span>
            </a>
            <a href="/drops" class="bg-white/[0.02] border border-white/[0.06] p-5 hover:border-hd-gold/20 transition-all group">
              <div class="text-2xl mb-3">💎</div>
              <p class="text-white font-light text-sm">Limited Drops</p>
              <p class="text-white/30 text-xs mt-1">Exclusive releases</p>
              <span class="mono text-[8px] text-hd-gold/50 group-hover:text-hd-gold transition-colors mt-3 block uppercase tracking-wider">→ View Drops</span>
            </a>
            <a href="/heritage" class="bg-white/[0.02] border border-white/[0.06] p-5 hover:border-hd-gold/20 transition-all group">
              <div class="text-2xl mb-3">📖</div>
              <p class="text-white font-light text-sm">Heritage Stories</p>
              <p class="text-white/30 text-xs mt-1">Cultural narratives</p>
              <span class="mono text-[8px] text-hd-gold/50 group-hover:text-hd-gold transition-colors mt-3 block uppercase tracking-wider">→ Read More</span>
            </a>
          </div>
          <!-- Recent XP -->
          {#if xpEvents.length > 0}
            <div class="bg-white/[0.02] border border-white/[0.06] p-5">
              <p class="mono text-[9px] uppercase tracking-widest text-white/40 mb-3">Recent Activity</p>
              {#each xpEvents.slice(0,4) as ev}
                <div class="flex justify-between items-center py-2 border-b border-white/[0.04] last:border-0">
                  <span class="text-white/60 text-sm">{ev.reason ?? 'XP Earned'}</span>
                  <span class="mono text-[10px] text-hd-gold">+{ev.amount} XP</span>
                </div>
              {/each}
            </div>
          {/if}
          <!-- Sign out -->
          <button on:click={signOut} class="w-full py-3 border border-red-900/30 text-red-400/50 mono text-[9px] uppercase tracking-widest hover:border-red-500/40 hover:text-red-400 transition-all">
            Sign Out
          </button>
        </div>

      {:else if activeTab === 'orders'}
        <div in:fly={{ y: 10, duration: 300 }}>
          {#if orders.length === 0}
            <div class="text-center py-16">
              <p class="font-serif text-xl text-white/30">No orders yet</p>
              <a href="/shop" class="mono text-[9px] text-hd-gold/60 hover:text-hd-gold mt-3 block">Start Shopping →</a>
            </div>
          {:else}
            <div class="space-y-3">
              {#each orders as order}
                <div class="bg-white/[0.02] border border-white/[0.06] p-4">
                  <div class="flex justify-between items-start mb-2">
                    <div>
                      <p class="mono text-[8px] uppercase text-white/30">Order #{order.id?.slice(0,8).toUpperCase()}</p>
                      <p class="font-serif text-lg text-hd-gold mt-0.5">₦{order.total_amount?.toLocaleString()}</p>
                    </div>
                    <span class="mono text-[8px] uppercase px-2 py-1 border {STATUS_MAP[order.status]?.color ?? 'text-white/40'} border-current/20">
                      {STATUS_MAP[order.status]?.label ?? order.status}
                    </span>
                  </div>
                  <p class="text-white/30 text-xs">{order.items?.length ?? 0} item(s) · {new Date(order.created_at).toLocaleDateString()}</p>
                </div>
              {/each}
            </div>
          {/if}
        </div>

      {:else if activeTab === 'wishlist'}
        <div in:fly={{ y: 10, duration: 300 }}>
          {#if wishlist.length === 0}
            <div class="text-center py-16">
              <p class="font-serif text-xl text-white/30">No saved items</p>
              <a href="/shop" class="mono text-[9px] text-hd-gold/60 hover:text-hd-gold mt-3 block">Browse Collection →</a>
            </div>
          {:else}
            <div class="grid grid-cols-2 gap-3">
              {#each wishlist as item}
                <a href="/product/{item.product_id}" class="group">
                  <div class="aspect-[3/4] bg-white/[0.03] border border-white/[0.06] group-hover:border-hd-gold/20 transition-all overflow-hidden">
                    <img src={item.products?.images?.[0] ?? '/hd-logo.png'} alt={item.products?.name} class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                  </div>
                  <p class="text-white/70 text-sm mt-2 leading-snug">{item.products?.name ?? 'Product'}</p>
                  <p class="text-hd-gold mono text-sm">₦{item.products?.price?.toLocaleString() ?? '—'}</p>
                </a>
              {/each}
            </div>
          {/if}
        </div>

      {:else if activeTab === 'rewards'}
        <div class="space-y-4" in:fly={{ y: 10, duration: 300 }}>
          <div class="bg-gradient-to-br from-hd-gold/10 to-transparent border border-hd-gold/20 p-6">
            <p class="mono text-[9px] uppercase tracking-widest text-hd-gold/60 mb-2">Your Balance</p>
            <div class="flex items-baseline gap-2">
              <span class="font-serif text-4xl text-hd-gold">{$userProfile?.lee_balance ?? 0}</span>
              <span class="mono text-[10px] text-hd-gold/50 uppercase">LEE Points</span>
            </div>
            <p class="text-white/30 text-xs mt-2">Redeem for discounts on your next purchase</p>
          </div>
          <div class="bg-white/[0.02] border border-white/[0.06] p-5">
            <p class="mono text-[9px] uppercase tracking-widest text-white/40 mb-4">How to Earn</p>
            {#each [['Make a purchase','10 LEE per ₦1,000 spent'],['Write a review','50 LEE per review'],['Refer a friend','200 LEE per referral'],['Complete profile','100 LEE one-time']] as [action, reward]}
              <div class="flex justify-between py-3 border-b border-white/[0.04] last:border-0">
                <span class="text-white/60 text-sm">{action}</span>
                <span class="mono text-[9px] text-hd-gold/70">{reward}</span>
              </div>
            {/each}
          </div>
          <a href="/rewards" class="block w-full text-center bg-hd-gold text-black mono text-[10px] uppercase tracking-widest py-3 font-semibold hover:bg-hd-gold/90 transition-all">Claim Rewards →</a>
        </div>
      {/if}
    </div>
  {:else}
    <div class="flex flex-col items-center justify-center min-h-[80vh] gap-6" in:fade>
      <img src="/hd-logo.png" alt="HD" class="w-16 h-16 object-contain opacity-30" />
      <div class="text-center">
        <p class="font-serif text-2xl text-white mb-2">Sign in to your account</p>
        <p class="text-white/30 text-sm">Access your orders, rewards, and wishlist</p>
      </div>
      <a href="/auth" class="bg-hd-gold text-black mono text-[10px] uppercase tracking-widest px-8 py-3 font-semibold">Sign In</a>
    </div>
  {/if}
</div>
