// src/pages/Wishlist.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { WishlistItem } from '../api/entities';

export default function Wishlist() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    WishlistItem.list().then(setItems).finally(() => setLoading(false));
  }, []);

  const removeItem = async (id) => {
    await WishlistItem.delete(id);
    setItems(i => i.filter(x => x.id !== id));
  };

  const addToCart = (item) => {
    const cart = JSON.parse(localStorage.getItem('hd_cart') || '[]');
    const exists = cart.findIndex(c => c.id === item.product_id);
    if (exists >= 0) { cart[exists].quantity += 1; }
    else {
      cart.push({ id: item.product_id, name: item.product_name, price: item.product_price, image: item.product_image, quantity: 1 });
    }
    localStorage.setItem('hd_cart', JSON.stringify(cart));
    window.dispatchEvent(new Event('cartUpdated'));
  };

  return (
    <div className="min-h-screen bg-[#050505]">
      <div className="py-16 px-6 md:px-16 max-w-7xl mx-auto">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-6 h-px bg-[#C5A059]" />
          <span className="text-[#C5A059] text-xs uppercase tracking-[0.3em]">Saved Pieces</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-serif text-white font-light mb-12">Wishlist</h1>

        {loading ? (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-white/5">
            {[1,2,3,4].map(i => <div key={i} className="bg-[#050505] aspect-[3/4] animate-pulse bg-white/5" />)}
          </div>
        ) : items.length === 0 ? (
          <div className="text-center py-24 border border-white/5">
            <div className="text-[#C5A059]/30 text-5xl mb-6">♡</div>
            <p className="text-white/30 font-serif text-2xl mb-3">Nothing saved yet</p>
            <p className="text-white/20 text-sm mb-8">Heart pieces you love while browsing</p>
            <Link to="/shop" className="text-[#C5A059] text-xs uppercase tracking-[0.3em] border border-[#C5A059]/30 px-6 py-3 hover:bg-[#C5A059] hover:text-black transition-all">
              Browse Collection
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-white/5">
            {items.map(item => (
              <div key={item.id} className="bg-[#050505] group relative">
                <Link to={`/product/${item.product_id}`} className="block">
                  <div className="aspect-[3/4] overflow-hidden relative">
                    {item.product_image ? (
                      <img src={item.product_image} alt={item.product_name} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />
                    ) : (
                      <div className="w-full h-full bg-white/5 flex items-center justify-center">
                        <span className="text-white/20 text-4xl">✦</span>
                      </div>
                    )}
                  </div>
                  <div className="p-4">
                    <h3 className="text-white font-serif text-base leading-tight mb-1 group-hover:text-[#C5A059] transition-colors">{item.product_name}</h3>
                    <div className="text-[#C5A059] text-sm">₦{item.product_price?.toLocaleString()}</div>
                  </div>
                </Link>
                {/* Actions */}
                <div className="px-4 pb-4 flex gap-2">
                  <button
                    onClick={() => addToCart(item)}
                    className="flex-1 py-2 bg-[#C5A059] text-black text-xs uppercase tracking-[0.2em] font-bold hover:bg-white transition-colors"
                  >
                    Add to Cart
                  </button>
                  <button
                    onClick={() => removeItem(item.id)}
                    className="w-10 h-8 border border-white/10 text-white/30 hover:text-red-400 hover:border-red-400/30 transition-colors text-sm"
                  >
                    ✕
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// src/routes/wishlist/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { fade, fly } from 'svelte/transition';
  import { supabase } from '$lib/supabase';
  import { currentUser, isAuthenticated } from '$lib/stores/auth';
  import { cart } from '$lib/stores/cart';

  let items: any[] = [];
  let loading = true;

  onMount(async () => {
    if (!$isAuthenticated) { goto('/auth?redirect=/wishlist'); return; }
    const { data } = await supabase
      .from('wishlist')
      .select('*, product:products(id,name,price,images,department,sizes)')
      .eq('user_id', $currentUser!.id)
      .order('created_at', { ascending: false });
    items = data ?? [];
    loading = false;
  });

  async function remove(id: string) {
    await supabase.from('wishlist').delete().eq('id', id);
    items = items.filter(i => i.id !== id);
  }

  function addToCart(item: any) {
    const p = item.product;
    if (!p) return;
    cart.add({ id: p.id, product_id: p.id, name: p.name, price: p.price, image: p.images?.[0] ?? '', size: p.sizes?.[0], department: p.department });
  }
</script>

<svelte:head><title>Saved Items — House of Daraja</title></svelte:head>

<div class="min-h-screen bg-[#050505] py-6">
  <div class="max-w-4xl mx-auto px-4">
    <div class="mb-8">
      <p class="mono text-hd-gold/50 text-[9px] uppercase tracking-[0.4em] mb-1">Account</p>
      <h1 class="font-serif text-3xl text-white font-light">Saved Items</h1>
    </div>

    {#if loading}
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        {#each Array(4) as _}<div class="aspect-[3/4] bg-white/[0.03] animate-pulse"></div>{/each}
      </div>
    {:else if items.length === 0}
      <div class="text-center py-24" in:fade>
        <img src="/hd-logo.png" alt="" class="w-14 h-14 mx-auto mb-5 opacity-20 object-contain" />
        <p class="font-serif text-xl text-white/30">Nothing saved yet</p>
        <p class="text-white/20 text-sm mt-2">Browse the collection and save pieces you love</p>
        <a href="/shop" class="mono text-[9px] text-hd-gold/50 hover:text-hd-gold mt-6 block">Browse Shop →</a>
      </div>
    {:else}
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        {#each items as item, i (item.id)}
          <div class="group" in:fly={{ y: 10, delay: i * 50 }}>
            <div class="relative aspect-[3/4] overflow-hidden bg-white/[0.03] border border-white/[0.06] hover:border-hd-gold/20 transition-all">
              <a href="/product/{item.product?.id}">
                <img src={item.product?.images?.[0] ?? '/hd-logo.png'} alt={item.product?.name} class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
              </a>
              <button on:click={() => remove(item.id)} class="absolute top-2 right-2 w-7 h-7 bg-[#050505]/80 border border-white/10 flex items-center justify-center text-white/40 hover:text-red-400 hover:border-red-400/30 transition-all text-xs">✕</button>
              <button
                on:click={() => addToCart(item)}
                class="absolute bottom-2 left-2 right-2 bg-hd-gold text-black mono text-[7px] uppercase tracking-widest py-2 opacity-0 group-hover:opacity-100 transition-all translate-y-1 group-hover:translate-y-0 font-semibold"
              >Add to Cart</button>
            </div>
            <a href="/product/{item.product?.id}">
              <p class="text-white/70 text-sm mt-2 leading-snug truncate">{item.product?.name}</p>
              <p class="text-hd-gold mono text-sm">₦{item.product?.price?.toLocaleString()}</p>
            </a>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>
