// src/routes/checkout/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { fade } from 'svelte/transition';
  import { cart, cartTotal } from '$lib/stores/cart';
  import { isAuthenticated, currentUser } from '$lib/stores/auth';
  import { supabase } from '$lib/supabase';

  let step: 'details' | 'payment' | 'confirm' = 'details';
  let loading = false;
  let orderId = '';

  let form = {
    name: '', email: '', phone: '', address: '', city: '', state: '', notes: ''
  };

  async function placeOrder() {
    loading = true;
    try {
      const ref = `HD-${Date.now().toString(36).toUpperCase()}`;
      const { data, error } = await supabase.from('orders').insert({
        user_id: $currentUser?.id ?? 'guest',
        items: $cart,
        total_amount: $cartTotal,
        status: 'pending',
        payment_status: 'pending',
        payment_reference: ref,
        shipping_address: { ...form },
        notes: form.notes,
      }).select().single();

      if (!error && data) {
        orderId = data.id;
        cart.clear();
        step = 'confirm';
      }
    } finally {
      loading = false;
    }
  }

  const NIGERIAN_STATES = ['Abuja','Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara'];
</script>

<svelte:head><title>Checkout — House of Daraja</title></svelte:head>

<div class="min-h-screen bg-[#050505] pt-20 pb-32">
  <div class="max-w-2xl mx-auto px-4">
    <!-- Steps indicator -->
    <div class="flex items-center justify-center gap-0 mb-12">
      {#each [['details','Details'], ['payment','Payment'], ['confirm','Confirmed']] as [s, label], i}
        <div class="flex items-center">
          <div class="flex flex-col items-center">
            <div class="w-8 h-8 rounded-full border-2 flex items-center justify-center mono text-[10px] font-bold transition-all {step === s ? 'border-hd-gold text-hd-gold bg-hd-gold/10' : 'border-white/20 text-white/30'}">
              {i+1}
            </div>
            <span class="mono text-[8px] uppercase tracking-wider mt-1 {step === s ? 'text-hd-gold' : 'text-white/20'}">{label}</span>
          </div>
          {#if i < 2}
            <div class="w-16 h-px bg-white/10 mx-2 mb-4"></div>
          {/if}
        </div>
      {/each}
    </div>

    {#if step === 'details'}
      <div in:fade>
        <h2 class="font-serif text-2xl text-white mb-6">Delivery Details</h2>
        <div class="space-y-4">
          {#each [['name','Full Name','text'],['email','Email Address','email'],['phone','Phone Number','tel']] as [field, label, type]}
            <div>
              <label class="mono text-[9px] uppercase tracking-widest text-white/40 block mb-1.5">{label}</label>
              <input
                bind:value={form[field]}
                type={type}
                class="w-full bg-white/[0.04] border border-white/[0.08] text-white px-4 py-3 text-sm focus:border-hd-gold/50 focus:outline-none transition-colors placeholder-white/20"
                placeholder={label}
              />
            </div>
          {/each}
          <div>
            <label class="mono text-[9px] uppercase tracking-widest text-white/40 block mb-1.5">Delivery Address</label>
            <textarea bind:value={form.address} rows="2" class="w-full bg-white/[0.04] border border-white/[0.08] text-white px-4 py-3 text-sm focus:border-hd-gold/50 focus:outline-none resize-none transition-colors placeholder-white/20" placeholder="Street address..."></textarea>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="mono text-[9px] uppercase tracking-widest text-white/40 block mb-1.5">City</label>
              <input bind:value={form.city} class="w-full bg-white/[0.04] border border-white/[0.08] text-white px-4 py-3 text-sm focus:border-hd-gold/50 focus:outline-none transition-colors placeholder-white/20" placeholder="City" />
            </div>
            <div>
              <label class="mono text-[9px] uppercase tracking-widest text-white/40 block mb-1.5">State</label>
              <select bind:value={form.state} class="w-full bg-white/[0.04] border border-white/[0.08] text-white px-4 py-3 text-sm focus:border-hd-gold/50 focus:outline-none transition-colors">
                <option value="" class="bg-[#050505]">Select State</option>
                {#each NIGERIAN_STATES as state}
                  <option value={state} class="bg-[#050505]">{state}</option>
                {/each}
              </select>
            </div>
          </div>
          <div>
            <label class="mono text-[9px] uppercase tracking-widest text-white/40 block mb-1.5">Order Notes (optional)</label>
            <textarea bind:value={form.notes} rows="2" class="w-full bg-white/[0.04] border border-white/[0.08] text-white px-4 py-3 text-sm focus:border-hd-gold/50 focus:outline-none resize-none transition-colors placeholder-white/20" placeholder="Special instructions..."></textarea>
          </div>
        </div>
        <button
          on:click={() => step = 'payment'}
          disabled={!form.name || !form.phone || !form.address}
          class="w-full mt-8 bg-hd-gold text-black mono text-[10px] uppercase tracking-widest py-4 font-semibold hover:bg-hd-gold/90 transition-all disabled:opacity-40"
        >
          Continue to Payment →
        </button>
      </div>

    {:else if step === 'payment'}
      <div in:fade>
        <h2 class="font-serif text-2xl text-white mb-6">Order Summary</h2>
        <div class="bg-white/[0.02] border border-white/[0.06] p-5 space-y-3 mb-6">
          {#each $cart as item}
            <div class="flex justify-between items-center text-sm">
              <span class="text-white/70">{item.name} {item.size ? `(${item.size})` : ''} × {item.quantity}</span>
              <span class="text-hd-gold mono">₦{(item.price * item.quantity).toLocaleString()}</span>
            </div>
          {/each}
          <div class="h-px bg-white/[0.06]"></div>
          <div class="flex justify-between font-semibold">
            <span class="text-white mono text-[10px] uppercase tracking-wider">Total</span>
            <span class="font-serif text-xl text-hd-gold">₦{$cartTotal.toLocaleString()}</span>
          </div>
        </div>
        <!-- OPay placeholder -->
        <div class="bg-white/[0.02] border border-hd-gold/20 p-5 mb-6">
          <div class="flex items-center gap-3 mb-4">
            <div class="w-8 h-8 bg-hd-gold/10 border border-hd-gold/30 flex items-center justify-center">
              <span class="text-hd-gold text-xs">₦</span>
            </div>
            <div>
              <p class="text-white text-sm font-medium">OPay Secure Checkout</p>
              <p class="text-white/40 text-xs">Cards, Bank Transfer, USSD</p>
            </div>
          </div>
          <p class="mono text-[9px] text-white/30 uppercase tracking-wider">Payment is secured by OPay. No card details stored.</p>
        </div>
        <button
          on:click={placeOrder}
          disabled={loading}
          class="w-full bg-hd-gold text-black mono text-[10px] uppercase tracking-widest py-4 font-semibold hover:bg-hd-gold/90 transition-all disabled:opacity-60 flex items-center justify-center gap-3"
        >
          {#if loading}
            <div class="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin"></div>
            Processing...
          {:else}
            Pay ₦{$cartTotal.toLocaleString()} via OPay
          {/if}
        </button>
        <button on:click={() => step = 'details'} class="w-full mt-2 text-white/30 text-sm mono uppercase tracking-widest py-3 hover:text-white/50 transition-colors">← Edit Details</button>
      </div>

    {:else}
      <div class="text-center py-12" in:fade>
        <div class="w-16 h-16 bg-hd-gold/10 border border-hd-gold/30 rounded-full flex items-center justify-center mx-auto mb-6">
          <svg class="w-8 h-8 text-hd-gold" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
          </svg>
        </div>
        <h2 class="font-serif text-3xl text-white mb-3">Order Confirmed</h2>
        <p class="text-white/40 text-sm mb-2">Your order has been placed successfully</p>
        {#if orderId}<p class="mono text-hd-gold/60 text-[9px] uppercase tracking-widest">Order ID: {orderId.slice(0,8).toUpperCase()}</p>{/if}
        <div class="mt-8 flex gap-3 justify-center">
          <a href="/orders" class="bg-hd-gold text-black mono text-[10px] uppercase tracking-widest px-6 py-3 font-semibold">Track Order</a>
          <a href="/shop" class="border border-white/10 text-white/60 mono text-[10px] uppercase tracking-widest px-6 py-3 hover:border-hd-gold/30 transition-colors">Shop More</a>
        </div>
      </div>
    {/if}
  </div>
</div>

// src/pages/Checkout.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Order } from '../api/entities';

const OPAY_MERCHANT_ID = import.meta.env.VITE_OPAY_MERCHANT_ID || '';
const OPAY_PUBLIC_KEY = import.meta.env.VITE_OPAY_PUBLIC_KEY || '';

export default function Checkout() {
  const navigate = useNavigate();
  const [items, setItems] = useState([]);
  const [step, setStep] = useState(1); // 1=details, 2=payment, 3=success
  const [processing, setProcessing] = useState(false);
  const [orderId, setOrderId] = useState(null);
  const [form, setForm] = useState({
    full_name: '', email: '', phone: '',
    address: '', city: '', state: '', country: 'Nigeria',
  });

  useEffect(() => {
    const cart = JSON.parse(localStorage.getItem('hd_cart') || '[]');
    if (cart.length === 0) navigate('/shop');
    setItems(cart);
  }, []);

  const total = items.reduce((s, i) => s + i.price * i.quantity, 0);
  const deliveryFee = total >= 100000 ? 0 : 5000;
  const grandTotal = total + deliveryFee;

  const generateRef = () => `HD-${Date.now()}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`;

  const createOrder = async () => {
    const ref = generateRef();
    const order = await Order.create({
      items,
      total_amount: grandTotal,
      status: 'pending',
      payment_status: 'pending',
      payment_reference: ref,
      shipping_address: `${form.address}, ${form.city}, ${form.state}, ${form.country}`,
      notes: `Contact: ${form.phone}`,
    });
    return { order, ref };
  };

  const handleOPayCheckout = async () => {
    setProcessing(true);
    try {
      const { order, ref } = await createOrder();
      setOrderId(order.id);

      // OPay inline checkout
      const opayConfig = {
        merchantId: OPAY_MERCHANT_ID,
        reference: ref,
        amount: grandTotal * 100, // in kobo
        currency: 'NGN',
        customerName: form.full_name,
        customerEmail: form.email,
        customerPhone: form.phone,
        callbackUrl: `${window.location.origin}/checkout/verify`,
        onSuccess: async (response) => {
          // Update order on success
          await Order.update(order.id, {
            payment_status: 'paid',
            status: 'confirmed',
            payment_reference: response.reference || ref,
          });
          localStorage.removeItem('hd_cart');
          window.dispatchEvent(new Event('cartUpdated'));

          // Trigger push notification
          if ('Notification' in window && Notification.permission === 'granted') {
            new Notification('Order Confirmed ✦', {
              body: `Your order of ₦${grandTotal.toLocaleString()} has been confirmed. House of Daraja`,
              icon: '/hd-icon.png',
              badge: '/hd-icon.png',
            });
          }

          setStep(3);
        },
        onFailure: (err) => {
          Order.update(order.id, { payment_status: 'failed' });
          alert('Payment failed. Please try again.');
          setProcessing(false);
        },
        onClose: () => {
          setProcessing(false);
        },
      };

      // Load OPay SDK and initiate
      if (window.OPay) {
        window.OPay.initialize(opayConfig);
      } else {
        // Fallback: redirect to OPay hosted page
        const params = new URLSearchParams({
          merchantId: OPAY_MERCHANT_ID,
          reference: ref,
          amount: grandTotal * 100,
          currency: 'NGN',
          name: form.full_name,
          email: form.email,
          phone: form.phone,
          callbackUrl: encodeURIComponent(`${window.location.origin}/checkout/verify?ref=${ref}&orderId=${order.id}`),
        });
        window.location.href = `https://cashier.opayweb.com/checkout?${params}`;
      }
    } catch (err) {
      alert('Could not initialize payment. Please try again.');
      setProcessing(false);
    }
  };

  if (step === 3) {
    return (
      <div className="min-h-screen bg-[#050505] flex items-center justify-center px-6">
        <div className="max-w-md w-full text-center">
          <div className="text-[#C5A059] text-7xl mb-8">✦</div>
          <h1 className="text-4xl font-serif text-white font-light mb-4">Order Confirmed</h1>
          <p className="text-white/50 mb-4">
            Your acquisition has been received. Our atelier is preparing your order.
          </p>
          <div className="bg-[#C5A059]/10 border border-[#C5A059]/20 p-4 mb-8">
            <div className="text-[#C5A059] text-xs uppercase tracking-[0.3em] mb-1">Order Total</div>
            <div className="text-white font-serif text-3xl">₦{grandTotal.toLocaleString()}</div>
          </div>
          <p className="text-white/30 text-sm mb-8">
            A confirmation has been sent to {form.email}. Track your order in your profile.
          </p>
          <div className="flex gap-4 justify-center">
            <Link to="/orders" className="bg-[#C5A059] text-black px-8 py-3 text-xs uppercase tracking-[0.3em] font-bold hover:bg-white transition-colors">
              Track Order
            </Link>
            <Link to="/" className="border border-white/20 text-white/60 px-8 py-3 text-xs uppercase tracking-[0.3em] hover:border-white/60 transition-colors">
              Continue Shopping
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#050505]">
      <div className="max-w-6xl mx-auto px-6 md:px-16 py-12">
        {/* Header */}
        <div className="flex items-center gap-3 mb-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-[#C5A059] flex items-center justify-center">
              <span className="text-black font-serif font-bold text-sm">HD</span>
            </div>
          </Link>
          <div className="w-px h-6 bg-white/10" />
          <span className="text-white/40 text-xs uppercase tracking-[0.3em]">Checkout</span>
        </div>

        {/* Progress */}
        <div className="flex items-center gap-3 mb-12 mt-6">
          {[
            { n: 1, label: 'Details' },
            { n: 2, label: 'Payment' },
          ].map(({ n, label }) => (
            <React.Fragment key={n}>
              <div className="flex items-center gap-2">
                <div className={`w-6 h-6 flex items-center justify-center text-xs font-bold ${
                  step >= n ? 'bg-[#C5A059] text-black' : 'bg-white/10 text-white/40'
                }`}>{n}</div>
                <span className={`text-xs uppercase tracking-[0.2em] ${step >= n ? 'text-white' : 'text-white/30'}`}>{label}</span>
              </div>
              {n < 2 && <div className={`flex-1 max-w-12 h-px ${step > n ? 'bg-[#C5A059]' : 'bg-white/10'}`} />}
            </React.Fragment>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-5 gap-12">
          {/* Left — form 62% */}
          <div className="lg:col-span-3">
            {step === 1 && (
              <form onSubmit={(e) => { e.preventDefault(); setStep(2); }}>
                <h2 className="text-2xl font-serif text-white font-light mb-8">Delivery Details</h2>
                <div className="space-y-5">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div>
                      <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Full Name *</label>
                      <input type="text" value={form.full_name} onChange={e => setForm(f => ({ ...f, full_name: e.target.value }))}
                        required placeholder="Your full name"
                        className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] placeholder-white/20" />
                    </div>
                    <div>
                      <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Phone *</label>
                      <input type="tel" value={form.phone} onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}
                        required placeholder="+234 xxx xxxx xxxx"
                        className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] placeholder-white/20" />
                    </div>
                  </div>
                  <div>
                    <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Email *</label>
                    <input type="email" value={form.email} onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
                      required placeholder="your@email.com"
                      className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] placeholder-white/20" />
                  </div>
                  <div>
                    <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">Delivery Address *</label>
                    <input type="text" value={form.address} onChange={e => setForm(f => ({ ...f, address: e.target.value }))}
                      required placeholder="Street address"
                      className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] placeholder-white/20" />
                  </div>
                  <div className="grid grid-cols-2 gap-5">
                    <div>
                      <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">City *</label>
                      <input type="text" value={form.city} onChange={e => setForm(f => ({ ...f, city: e.target.value }))}
                        required placeholder="City"
                        className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] placeholder-white/20" />
                    </div>
                    <div>
                      <label className="text-white/40 text-xs uppercase tracking-[0.3em] block mb-2">State *</label>
                      <input type="text" value={form.state} onChange={e => setForm(f => ({ ...f, state: e.target.value }))}
                        required placeholder="State"
                        className="w-full bg-[#0E0E0E] border border-white/10 text-white px-4 py-3 text-sm focus:outline-none focus:border-[#C5A059] placeholder-white/20" />
                    </div>
                  </div>
                </div>
                <button type="submit" className="w-[61.8%] bg-[#C5A059] text-black py-4 text-sm uppercase tracking-[0.3em] font-bold hover:bg-white transition-colors mt-8">
                  Continue to Payment →
                </button>
              </form>
            )}

            {step === 2 && (
              <div>
                <h2 className="text-2xl font-serif text-white font-light mb-8">Payment</h2>

                {/* OPay badge */}
                <div className="border border-[#C5A059]/20 p-6 mb-8 bg-[#C5A059]/5">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-12 h-12 bg-[#C5A059] flex items-center justify-center text-black font-bold text-xs">
                      OPay
                    </div>
                    <div>
                      <div className="text-white font-medium text-sm">OPay Secure Checkout</div>
                      <div className="text-white/40 text-xs mt-0.5">Bank transfer, card, USSD, wallets</div>
                    </div>
                    <div className="ml-auto flex items-center gap-1">
                      <div className="w-2 h-2 bg-green-400 rounded-full" />
                      <span className="text-green-400 text-xs">Secured</span>
                    </div>
                  </div>
                  <div className="space-y-2 text-xs text-white/40">
                    {[
                      '256-bit SSL encryption',
                      'Bank-grade security by OPay',
                      'Instant confirmation',
                      'Supports OPay wallet, cards, bank transfer, USSD',
                    ].map(f => (
                      <div key={f} className="flex items-center gap-2">
                        <span className="text-[#C5A059]">✓</span> {f}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Order summary recap */}
                <div className="space-y-3 mb-8 p-6 bg-[#0E0E0E] border border-white/5">
                  <div className="text-white/40 text-xs uppercase tracking-[0.3em] mb-4">Delivery to</div>
                  <div className="text-white/70 text-sm">{form.full_name}</div>
                  <div className="text-white/50 text-sm">{form.address}, {form.city}, {form.state}</div>
                  <div className="text-white/50 text-sm">{form.phone}</div>
                </div>

                <div className="flex gap-4">
                  <button onClick={handleOPayCheckout} disabled={processing}
                    className="flex-1 bg-[#C5A059] text-black py-4 text-sm uppercase tracking-[0.3em] font-bold hover:bg-white transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {processing ? 'Initializing OPay...' : `Pay ₦${grandTotal.toLocaleString()}`}
                  </button>
                  <button onClick={() => setStep(1)} className="px-6 border border-white/20 text-white/50 text-xs uppercase tracking-[0.2em] hover:border-white/50 transition-colors">
                    ← Back
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Right — order summary 38% */}
          <div className="lg:col-span-2">
            <div className="sticky top-24">
              <h3 className="text-white/40 text-xs uppercase tracking-[0.3em] mb-6">Order Summary</h3>
              <div className="space-y-4 mb-6">
                {items.map((item, i) => (
                  <div key={i} className="flex gap-3">
                    {item.image && (
                      <div className="relative">
                        <img src={item.image} alt={item.name} className="w-16 h-16 object-cover" />
                        <span className="absolute -top-2 -right-2 bg-[#C5A059] text-black text-[9px] w-5 h-5 rounded-full flex items-center justify-center font-bold">
                          {item.quantity}
                        </span>
                      </div>
                    )}
                    <div className="flex-1">
                      <div className="text-white text-sm leading-tight">{item.name}</div>
                      {item.size && <div className="text-white/40 text-xs">Size: {item.size}</div>}
                    </div>
                    <div className="text-white/70 text-sm whitespace-nowrap">₦{(item.price * item.quantity).toLocaleString()}</div>
                  </div>
                ))}
              </div>

              <div className="border-t border-white/10 pt-4 space-y-3 mb-6">
                <div className="flex justify-between text-sm">
                  <span className="text-white/40">Subtotal</span>
                  <span className="text-white/70">₦{total.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-white/40">Delivery</span>
                  <span className={deliveryFee === 0 ? 'text-green-400 text-sm' : 'text-white/70 text-sm'}>
                    {deliveryFee === 0 ? 'Free' : `₦${deliveryFee.toLocaleString()}`}
                  </span>
                </div>
                {deliveryFee === 0 && (
                  <div className="text-[#C5A059] text-xs">✓ Free delivery on orders above ₦100,000</div>
                )}
              </div>

              <div className="flex justify-between items-center pt-4 border-t border-white/10">
                <span className="text-white/50 uppercase tracking-[0.2em] text-xs">Total</span>
                <span className="text-white font-serif text-3xl">₦{grandTotal.toLocaleString()}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
