// src/routes/orders/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { fade, fly } from 'svelte/transition';
  import { supabase } from '$lib/supabase';
  import { currentUser, isAuthenticated } from '$lib/stores/auth';

  let orders: any[] = [];
  let loading = true;
  let activeTab: 'all' | 'active' | 'delivered' = 'all';

  const ORDER_STEPS = ['confirmed','processing','shipped','out_for_delivery','delivered'];
  const STATUS_CONFIG: Record<string, {label:string;color:string;step:number}> = {
    pending:         { label:'Pending',          color:'text-white/40',  step:0 },
    confirmed:       { label:'Confirmed',        color:'text-blue-400',  step:1 },
    processing:      { label:'Processing',       color:'text-yellow-400',step:2 },
    shipped:         { label:'Shipped',          color:'text-orange-400',step:3 },
    out_for_delivery:{ label:'Out for Delivery', color:'text-amber-400', step:4 },
    delivered:       { label:'Delivered',        color:'text-green-400', step:5 },
    cancelled:       { label:'Cancelled',        color:'text-red-400',   step:0 },
  };

  onMount(async () => {
    if (!$isAuthenticated) { goto('/auth?redirect=/orders'); return; }
    const { data } = await supabase.from('orders').select('*').eq('user_id', $currentUser!.id).order('created_at', { ascending: false });
    orders = data ?? [];
    loading = false;
  });

  $: filteredOrders = activeTab === 'all' ? orders
    : activeTab === 'delivered' ? orders.filter(o => o.status === 'delivered')
    : orders.filter(o => !['delivered','cancelled'].includes(o.status));
</script>

<svelte:head><title>My Orders — House of Daraja</title></svelte:head>

<div class="min-h-screen bg-[#050505] py-6">
  <div class="max-w-2xl mx-auto px-4">
    <div class="mb-8">
      <p class="mono text-hd-gold/50 text-[9px] uppercase tracking-[0.4em] mb-1">Account</p>
      <h1 class="font-serif text-3xl text-white font-light">My Orders</h1>
    </div>

    <!-- Tabs -->
    <div class="flex border-b border-white/[0.06] mb-6">
      {#each [['all','All'],['active','Active'],['delivered','Delivered']] as [tab, label]}
        <button
          on:click={() => activeTab = tab}
          class="flex-1 py-3 mono text-[9px] uppercase tracking-widest border-b-2 transition-all {activeTab === tab ? 'border-hd-gold text-hd-gold' : 'border-transparent text-white/30'}"
        >{label}</button>
      {/each}
    </div>

    {#if loading}
      <div class="space-y-4">{#each Array(3) as _}<div class="h-32 bg-white/[0.03] animate-pulse"></div>{/each}</div>
    {:else if filteredOrders.length === 0}
      <div class="text-center py-20" in:fade>
        <img src="/hd-logo.png" alt="" class="w-14 h-14 mx-auto mb-5 opacity-20 object-contain" />
        <p class="font-serif text-xl text-white/30">No orders here yet</p>
        <a href="/shop" class="mono text-[9px] text-hd-gold/50 hover:text-hd-gold mt-4 block">Browse the Collection →</a>
      </div>
    {:else}
      <div class="space-y-4">
        {#each filteredOrders as order, i (order.id)}
          <div class="bg-white/[0.02] border border-white/[0.06] overflow-hidden" in:fly={{ y: 10, delay: i * 60 }}>
            <!-- Order header -->
            <div class="flex items-center justify-between px-4 pt-4 pb-3 border-b border-white/[0.04]">
              <div>
                <p class="mono text-[8px] uppercase text-white/30 tracking-wider">Order #{order.id?.slice(0,8).toUpperCase()}</p>
                <p class="text-white/50 text-xs mt-0.5">{new Date(order.created_at).toLocaleDateString('en-NG', { day:'numeric', month:'long', year:'numeric' })}</p>
              </div>
              <div class="text-right">
                <span class="mono text-[8px] uppercase {STATUS_CONFIG[order.status]?.color ?? 'text-white/40'}">{STATUS_CONFIG[order.status]?.label ?? order.status}</span>
                <p class="font-serif text-lg text-hd-gold mt-0.5">₦{order.total_amount?.toLocaleString()}</p>
              </div>
            </div>

            <!-- Progress tracker (for active orders) -->
            {#if !['pending','cancelled','delivered'].includes(order.status)}
              {@const step = STATUS_CONFIG[order.status]?.step ?? 0}
              <div class="px-4 py-4 border-b border-white/[0.04]">
                <div class="flex items-center">
                  {#each ORDER_STEPS as s, si}
                    <div class="flex-1 flex items-center">
                      <div class="w-3 h-3 rounded-full border-2 flex-shrink-0 transition-all {si < step ? 'bg-hd-gold border-hd-gold' : si === step-1 ? 'border-hd-gold bg-hd-gold/20 animate-pulse' : 'border-white/20'}"></div>
                      {#if si < ORDER_STEPS.length - 1}
                        <div class="flex-1 h-px transition-all {si < step-1 ? 'bg-hd-gold' : 'bg-white/10'}"></div>
                      {/if}
                    </div>
                  {/each}
                </div>
                <div class="flex justify-between mt-2">
                  {#each ORDER_STEPS as s}
                    <span class="mono text-[6px] uppercase text-white/20 capitalize flex-1 text-center">{s.replace('_',' ')}</span>
                  {/each}
                </div>
              </div>
            {/if}

            <!-- Items preview -->
            <div class="px-4 pb-4 pt-3">
              <div class="flex gap-2 mb-3 overflow-x-auto scrollbar-none">
                {#each (order.items ?? []).slice(0,4) as item}
                  <div class="flex-shrink-0 w-12 h-14 overflow-hidden bg-white/[0.04]">
                    <img src={item.image ?? '/hd-logo.png'} alt={item.name} class="w-full h-full object-cover" />
                  </div>
                {/each}
                {#if (order.items?.length ?? 0) > 4}
                  <div class="flex-shrink-0 w-12 h-14 bg-white/[0.04] flex items-center justify-center">
                    <span class="mono text-[8px] text-white/30">+{order.items.length - 4}</span>
                  </div>
                {/if}
              </div>
              {#if order.tracking_number}
                <div class="flex items-center gap-2">
                  <span class="mono text-[8px] text-white/30 uppercase">Tracking:</span>
                  <span class="mono text-[9px] text-hd-gold/70">{order.tracking_number}</span>
                </div>
              {/if}
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

// src/pages/Orders.jsx
import React, { useState, useEffect } from 'react';
import { Order } from '../api/entities';

const STATUS_STEPS = ['pending', 'confirmed', 'processing', 'shipped', 'delivered'];

const STATUS_CONFIG = {
  pending: { color: 'text-yellow-400', bg: 'bg-yellow-400/10', label: 'Pending' },
  confirmed: { color: 'text-blue-400', bg: 'bg-blue-400/10', label: 'Confirmed' },
  processing: { color: 'text-purple-400', bg: 'bg-purple-400/10', label: 'Processing' },
  shipped: { color: 'text-cyan-400', bg: 'bg-cyan-400/10', label: 'Shipped' },
  delivered: { color: 'text-green-400', bg: 'bg-green-400/10', label: 'Delivered' },
  cancelled: { color: 'text-red-400', bg: 'bg-red-400/10', label: 'Cancelled' },
  refunded: { color: 'text-white/40', bg: 'bg-white/5', label: 'Refunded' },
};

export default function Orders() {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState(null);

  useEffect(() => {
    Order.list().then(o => {
      setOrders(o.sort((a, b) => new Date(b.created_date) - new Date(a.created_date)));
    }).finally(() => setLoading(false));
  }, []);

  return (
    <div className="min-h-screen bg-[#050505]">
      <div className="py-16 px-6 md:px-16 max-w-4xl mx-auto">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-6 h-px bg-[#C5A059]" />
          <span className="text-[#C5A059] text-xs uppercase tracking-[0.3em]">Purchase History</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-serif text-white font-light mb-12">My Orders</h1>

        {loading ? (
          <div className="space-y-4">
            {[1,2,3].map(i => (
              <div key={i} className="h-24 bg-white/5 animate-pulse" />
            ))}
          </div>
        ) : orders.length === 0 ? (
          <div className="text-center py-24 border border-white/5">
            <div className="text-[#C5A059]/40 text-5xl mb-6">✦</div>
            <p className="text-white/30 font-serif text-2xl mb-3">No orders yet</p>
            <p className="text-white/20 text-sm mb-8">Your acquisitions will appear here</p>
            <a href="/shop" className="text-[#C5A059] text-xs uppercase tracking-[0.3em] border border-[#C5A059]/30 px-6 py-3 hover:bg-[#C5A059] hover:text-black transition-all">
              Browse Collection
            </a>
          </div>
        ) : (
          <div className="space-y-3">
            {orders.map(order => {
              const statusInfo = STATUS_CONFIG[order.status] || STATUS_CONFIG.pending;
              const isExpanded = expandedId === order.id;
              const stepIndex = STATUS_STEPS.indexOf(order.status);

              return (
                <div key={order.id} className="border border-white/10 hover:border-white/20 transition-colors">
                  <button
                    onClick={() => setExpandedId(isExpanded ? null : order.id)}
                    className="w-full p-6 flex items-center justify-between text-left"
                  >
                    <div className="flex items-center gap-6">
                      <div>
                        <div className="text-white/30 text-xs uppercase tracking-[0.2em] mb-1">
                          {new Date(order.created_date).toLocaleDateString('en-NG', { year: 'numeric', month: 'short', day: 'numeric' })}
                        </div>
                        <div className="text-white font-serif text-lg">
                          ₦{order.total_amount?.toLocaleString()}
                        </div>
                        <div className="text-white/40 text-xs mt-1">
                          {order.items?.length || 0} item{order.items?.length !== 1 ? 's' : ''}
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-4">
                      <div className={`text-xs uppercase tracking-[0.2em] px-3 py-1 ${statusInfo.color} ${statusInfo.bg}`}>
                        {statusInfo.label}
                      </div>
                      <span className="text-white/30 transition-transform" style={{ transform: isExpanded ? 'rotate(180deg)' : 'none' }}>
                        ▾
                      </span>
                    </div>
                  </button>

                  {isExpanded && (
                    <div className="px-6 pb-6 border-t border-white/5">
                      {/* Progress tracker */}
                      {order.status !== 'cancelled' && order.status !== 'refunded' && (
                        <div className="py-6 mb-6">
                          <div className="flex items-center justify-between relative">
                            <div className="absolute top-3 left-0 right-0 h-px bg-white/10" />
                            <div
                              className="absolute top-3 left-0 h-px bg-[#C5A059] transition-all"
                              style={{ width: `${stepIndex >= 0 ? (stepIndex / (STATUS_STEPS.length - 1)) * 100 : 0}%` }}
                            />
                            {STATUS_STEPS.map((step, i) => (
                              <div key={step} className="relative flex flex-col items-center gap-2">
                                <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center text-[10px] ${
                                  i <= stepIndex
                                    ? 'border-[#C5A059] bg-[#C5A059] text-black'
                                    : 'border-white/20 bg-[#050505] text-white/30'
                                }`}>
                                  {i < stepIndex ? '✓' : i + 1}
                                </div>
                                <span className={`text-[9px] uppercase tracking-[0.15em] ${i <= stepIndex ? 'text-[#C5A059]' : 'text-white/20'}`}>
                                  {step}
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {/* Items */}
                      <div className="space-y-3 mb-6">
                        {order.items?.map((item, i) => (
                          <div key={i} className="flex items-center gap-4">
                            {item.image && (
                              <img src={item.image} alt={item.name} className="w-16 h-16 object-cover" />
                            )}
                            <div className="flex-1">
                              <div className="text-white text-sm">{item.name}</div>
                              {item.size && <div className="text-white/40 text-xs">Size: {item.size}</div>}
                              <div className="text-white/40 text-xs">Qty: {item.quantity}</div>
                            </div>
                            <div className="text-[#C5A059] text-sm">₦{(item.price * item.quantity)?.toLocaleString()}</div>
                          </div>
                        ))}
                      </div>

                      {/* Shipping & tracking */}
                      <div className="grid grid-cols-2 gap-4 pt-4 border-t border-white/5 text-sm">
                        {order.shipping_address && (
                          <div>
                            <div className="text-white/30 text-xs uppercase tracking-[0.2em] mb-1">Ship To</div>
                            <div className="text-white/60">{order.shipping_address}</div>
                          </div>
                        )}
                        {order.tracking_number && (
                          <div>
                            <div className="text-white/30 text-xs uppercase tracking-[0.2em] mb-1">Tracking</div>
                            <div className="text-[#C5A059]">{order.tracking_number}</div>
                          </div>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
