// src/routes/rewards/+page.svelte
<script lang="ts">
  import { fade, fly } from 'svelte/transition';
  import { userProfile, isAuthenticated } from '$lib/stores/auth';
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';

  const TIERS = [
    { id:'citizen',  label:'Citizen',      minXP:0,     color:'#FFFFFF', perks:['5% off first order','Access to public drops','Basic Leema AI'] },
    { id:'patron',   label:'Patron',       minXP:500,   color:'#F59E0B', perks:['10% discount on all orders','Priority drop access','Extended Leema AI','Free standard shipping'] },
    { id:'curator',  label:'Curator',      minXP:2000,  color:'#C5A059', perks:['15% discount','Curator-only drops','Dedicated style concierge','Express shipping included','1 free Atelier consultation/yr'] },
    { id:'vanguard', label:'Vanguard',     minXP:7500,  color:'#A855F7', perks:['20% discount','First access to all drops','Monthly gift from Daraja','VIP event invitations','Free express shipping always'] },
    { id:'elite',    label:'Daraja Elite', minXP:25000, color:'#C5A059', perks:['25% discount on everything','Private drops before anyone else','Annual bespoke piece (gifted)','Daraja Concierge hotline 24/7','Name on the House of Daraja Wall'] },
  ];

  const EARN_WAYS = [
    { action:'Make a Purchase',      reward:'10 LEE per ₦1,000',  icon:'🛍️' },
    { action:'Write a Review',       reward:'50 LEE per review',  icon:'⭐' },
    { action:'Refer a Friend',       reward:'200 LEE',            icon:'🤝' },
    { action:'Complete Profile',     reward:'100 LEE (one-time)', icon:'👤' },
    { action:'Join the Community',   reward:'25 LEE',             icon:'🏛️' },
    { action:'Share on Social',      reward:'15 LEE per share',   icon:'📢' },
    { action:'Bespoke Commission',   reward:'500 LEE',            icon:'✦' },
    { action:'Win an Auction',       reward:'300 LEE',            icon:'⚡' },
  ];

  onMount(() => { if (!$isAuthenticated) goto('/auth?redirect=/rewards'); });

  $: tier    = $userProfile?.prestige_tier ?? 'citizen';
  $: tierCfg = TIERS.find(t => t.id === tier) ?? TIERS[0];
  $: nextTier = TIERS[TIERS.findIndex(t => t.id === tier) + 1];
  $: xpProgress = $userProfile && nextTier ? Math.min(($userProfile.xp / nextTier.minXP) * 100, 100) : 100;
</script>

<svelte:head><title>Rewards — House of Daraja</title></svelte:head>

<div class="min-h-screen bg-[#050505] py-6">
  <div class="max-w-2xl mx-auto px-4">
    <div class="mb-8">
      <p class="mono text-hd-gold/50 text-[9px] uppercase tracking-[0.4em] mb-1">Prestige System</p>
      <h1 class="font-serif text-3xl text-white font-light">LEE Rewards</h1>
    </div>

    <!-- Current tier card -->
    {#if $userProfile}
      <div class="relative border overflow-hidden mb-8 p-6" style="border-color: {tierCfg.color}30; background: linear-gradient(135deg, {tierCfg.color}08 0%, transparent 100%);" in:fade>
        <div class="flex items-start justify-between mb-6">
          <div>
            <p class="mono text-[9px] uppercase tracking-[0.3em] mb-1" style="color:{tierCfg.color}80">Current Tier</p>
            <h2 class="font-serif text-3xl text-white">{tierCfg.label}</h2>
          </div>
          <div class="text-right">
            <p class="mono text-[8px] uppercase text-white/30 mb-1">Balance</p>
            <p class="font-serif text-3xl" style="color:{tierCfg.color}">{$userProfile.lee_balance ?? 0}</p>
            <p class="mono text-[7px] text-white/20 uppercase">LEE Points</p>
          </div>
        </div>

        <!-- XP Progress -->
        {#if nextTier}
          <div class="mb-4">
            <div class="flex justify-between mb-2">
              <span class="mono text-[8px] uppercase text-white/30">Progress to {nextTier.label}</span>
              <span class="mono text-[9px]" style="color:{tierCfg.color}">{$userProfile.xp?.toLocaleString()} / {nextTier.minXP.toLocaleString()} XP</span>
            </div>
            <div class="h-1.5 bg-white/[0.06] overflow-hidden">
              <div class="h-full transition-all duration-1000" style="width:{xpProgress}%; background: {tierCfg.color}"></div>
            </div>
          </div>
        {/if}

        <!-- Current perks -->
        <div>
          <p class="mono text-[8px] uppercase text-white/30 tracking-widest mb-3">Your Perks</p>
          <div class="grid grid-cols-1 gap-1.5">
            {#each tierCfg.perks as perk}
              <div class="flex items-center gap-2">
                <span style="color:{tierCfg.color}" class="text-xs">✓</span>
                <span class="text-white/60 text-sm">{perk}</span>
              </div>
            {/each}
          </div>
        </div>
      </div>
    {/if}

    <!-- Earn section -->
    <div class="mb-8">
      <h2 class="font-serif text-xl text-white mb-4">Earn LEE Points</h2>
      <div class="space-y-2">
        {#each EARN_WAYS as way, i}
          <div class="flex items-center justify-between py-3 px-4 bg-white/[0.02] border border-white/[0.06] hover:border-hd-gold/10 transition-all" in:fly={{ y: 5, delay: i * 40 }}>
            <div class="flex items-center gap-3">
              <span class="text-lg">{way.icon}</span>
              <span class="text-white/70 text-sm">{way.action}</span>
            </div>
            <span class="mono text-[9px] text-hd-gold/70">{way.reward}</span>
          </div>
        {/each}
      </div>
    </div>

    <!-- All tiers roadmap -->
    <div class="mb-8">
      <h2 class="font-serif text-xl text-white mb-4">Prestige Tiers</h2>
      <div class="space-y-3">
        {#each TIERS as t, i}
          {@const isActive = t.id === tier}
          {@const isAchieved = TIERS.findIndex(x=>x.id===tier) >= i}
          <div class="border p-4 transition-all {isActive ? 'border-hd-gold/30 bg-hd-gold/5' : isAchieved ? 'border-white/[0.08]' : 'border-white/[0.04] opacity-50'}">
            <div class="flex items-center justify-between mb-2">
              <div class="flex items-center gap-3">
                {#if isAchieved}<span class="text-sm" style="color:{t.color}">✦</span>{:else}<span class="text-white/20 text-sm">◈</span>{/if}
                <h3 class="font-serif text-base" style="color: {isAchieved ? t.color : 'rgba(255,255,255,0.3)'}">{t.label}</h3>
                {#if isActive}<span class="mono text-[7px] bg-hd-gold text-black px-1.5 py-0.5 ml-2">Current</span>{/if}
              </div>
              <span class="mono text-[8px] text-white/30">{t.minXP.toLocaleString()} XP</span>
            </div>
            {#if isActive || isAchieved}
              <div class="flex flex-wrap gap-x-4 gap-y-1 mt-2">
                {#each t.perks.slice(0,2) as perk}
                  <span class="text-white/40 text-xs">• {perk}</span>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      </div>
    </div>

    <!-- Redeem CTA -->
    {#if ($userProfile?.lee_balance ?? 0) > 0}
      <div class="bg-gradient-to-r from-hd-gold/10 to-transparent border border-hd-gold/20 p-5 flex items-center justify-between">
        <div>
          <p class="text-white font-light mb-1">Ready to redeem?</p>
          <p class="text-white/40 text-sm">{$userProfile?.lee_balance} LEE available</p>
        </div>
        <a href="/checkout" class="bg-hd-gold text-black mono text-[9px] uppercase tracking-widest px-5 py-2.5 font-semibold hover:bg-hd-gold/90 transition-all">Redeem Now</a>
      </div>
    {/if}
  </div>
</div>

// src/pages/Rewards.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { User } from '../api/entities';

const TIERS = [
  { name: 'Citizen', min: 0, max: 999, color: 'text-white/60', bg: 'bg-white/10', icon: '◎' },
  { name: 'Gold', min: 1000, max: 4999, color: 'text-[#C5A059]', bg: 'bg-[#C5A059]/20', icon: '◈' },
  { name: 'Platinum', min: 5000, max: 14999, color: 'text-blue-400', bg: 'bg-blue-400/20', icon: '◆' },
  { name: 'Diamond Elite', min: 15000, max: Infinity, color: 'text-purple-400', bg: 'bg-purple-400/20', icon: '✦' },
];

const REWARDS = [
  { id: 1, title: 'First Purchase', desc: 'Complete your first order', xp: 100, icon: '◈', unlocked: true },
  { id: 2, title: 'Heritage Seeker', desc: 'View 10 heritage posts', xp: 150, icon: '◆', unlocked: true },
  { id: 3, title: 'Atelier Initiate', desc: 'Submit a bespoke commission', xp: 500, icon: '✦', unlocked: false },
  { id: 4, title: 'Drop Hunter', desc: 'Purchase from 3 live drops', xp: 300, icon: '◉', unlocked: false },
  { id: 5, title: 'Sovereign Circle', desc: 'Reach Gold tier', xp: 1000, icon: '◈', unlocked: false },
  { id: 6, title: 'Neural Pioneer', desc: 'Chat with Leema 5 times', xp: 200, icon: '⬡', unlocked: true },
  { id: 7, title: 'Marketplace Patron', desc: 'Purchase from 5 vendors', xp: 400, icon: '◈', unlocked: false },
  { id: 8, title: 'Diamond Sovereign', desc: 'Reach Diamond Elite tier', xp: 5000, icon: '✦', unlocked: false },
];

const PERKS = {
  Citizen: ['Early access newsletters', 'Community forum access'],
  Gold: ['5% discount on all orders', 'Priority customer support', 'Early drop access (30min)'],
  Platinum: ['10% discount on all orders', 'Free shipping always', 'Early drop access (2hrs)', 'Atelier consultation'],
  'Diamond Elite': ['15% discount on all orders', 'Dedicated personal stylist', 'Exclusive Diamond drops', 'Complimentary bespoke fitting', 'VIP event invitations'],
};

export default function Rewards() {
  const [xp] = useState(1250);
  const [tab, setTab] = useState('overview');

  const currentTier = TIERS.find(t => xp >= t.min && xp <= t.max) || TIERS[0];
  const nextTier = TIERS[TIERS.indexOf(currentTier) + 1];
  const progress = nextTier ? ((xp - currentTier.min) / (nextTier.min - currentTier.min)) * 100 : 100;

  return (
    <div className="min-h-screen bg-[#050505] px-6 md:px-16 py-16 max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-6 h-px bg-[#C5A059]" />
          <span className="text-[#C5A059] text-xs uppercase tracking-[0.3em]">Sovereign Status</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-serif text-white font-light">Rewards</h1>
      </div>

      {/* Status Card — 62% / 38% golden split */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-6 mb-12">
        {/* Main status — 62% */}
        <div className="md:col-span-3 bg-[#0E0E0E] border border-white/5 p-8">
          <div className="flex items-start justify-between mb-8">
            <div>
              <div className={`text-4xl mb-2 ${currentTier.color}`}>{currentTier.icon}</div>
              <div className="text-white font-serif text-3xl font-light">{currentTier.name}</div>
              <div className="text-white/40 text-sm mt-1">Current Tier</div>
            </div>
            <div className="text-right">
              <div className="text-[#C5A059] font-mono text-3xl font-bold">{xp.toLocaleString()}</div>
              <div className="text-white/40 text-xs uppercase tracking-[0.2em] mt-1">XP Points</div>
            </div>
          </div>

          {nextTier && (
            <div>
              <div className="flex justify-between text-xs text-white/40 mb-2">
                <span>{currentTier.name}</span>
                <span>{nextTier.name} — {nextTier.min.toLocaleString()} XP</span>
              </div>
              <div className="h-1 bg-white/10 relative">
                <div
                  className="h-full bg-[#C5A059] transition-all duration-1000"
                  style={{ width: `${progress}%` }}
                />
              </div>
              <div className="text-white/40 text-xs mt-2">
                {(nextTier.min - xp).toLocaleString()} XP to reach {nextTier.name}
              </div>
            </div>
          )}
          {!nextTier && (
            <div className="text-[#C5A059] text-sm">✦ Maximum tier achieved — Diamond Elite</div>
          )}
        </div>

        {/* Perks — 38% */}
        <div className="md:col-span-2 bg-[#C5A059]/5 border border-[#C5A059]/20 p-6">
          <div className="text-[#C5A059] text-xs uppercase tracking-[0.3em] mb-4">Current Perks</div>
          <div className="space-y-3">
            {(PERKS[currentTier.name] || []).map((perk, i) => (
              <div key={i} className="flex items-start gap-3">
                <span className="text-[#C5A059] text-xs mt-0.5">✓</span>
                <span className="text-white/70 text-sm">{perk}</span>
              </div>
            ))}
          </div>
          {nextTier && (
            <div className="mt-6 pt-6 border-t border-white/10">
              <div className="text-white/30 text-xs uppercase tracking-[0.2em] mb-3">Unlock at {nextTier.name}</div>
              {(PERKS[nextTier.name] || []).slice(0, 2).map((perk, i) => (
                <div key={i} className="flex items-start gap-3 mb-2 opacity-40">
                  <span className="text-white/40 text-xs mt-0.5">◎</span>
                  <span className="text-white/50 text-sm">{perk}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-6 border-b border-white/10 mb-8">
        {[['overview', 'Overview'], ['achievements', 'Achievements'], ['tiers', 'All Tiers']].map(([k, l]) => (
          <button key={k} onClick={() => setTab(k)}
            className={`pb-4 text-xs uppercase tracking-[0.25em] border-b-2 transition-all -mb-px ${
              tab === k ? 'border-[#C5A059] text-[#C5A059]' : 'border-transparent text-white/40 hover:text-white'
            }`}
          >{l}</button>
        ))}
      </div>

      {/* Overview */}
      {tab === 'overview' && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'Total XP', value: xp.toLocaleString(), icon: '◈' },
            { label: 'Achievements', value: `${REWARDS.filter(r => r.unlocked).length}/${REWARDS.length}`, icon: '✦' },
            { label: 'Orders', value: '3', icon: '◆' },
            { label: 'Tier Rank', value: `#${TIERS.indexOf(currentTier) + 1}`, icon: '◎' },
          ].map(stat => (
            <div key={stat.label} className="bg-[#0E0E0E] border border-white/5 p-5">
              <div className="text-[#C5A059] text-xl mb-3">{stat.icon}</div>
              <div className="text-white font-serif text-2xl font-light">{stat.value}</div>
              <div className="text-white/40 text-xs uppercase tracking-[0.2em] mt-1">{stat.label}</div>
            </div>
          ))}
        </div>
      )}

      {/* Achievements */}
      {tab === 'achievements' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {REWARDS.map(r => (
            <div key={r.id} className={`flex items-center gap-4 p-5 border transition-all ${
              r.unlocked ? 'bg-[#C5A059]/5 border-[#C5A059]/20' : 'bg-[#0E0E0E] border-white/5 opacity-50'
            }`}>
              <div className={`w-12 h-12 flex items-center justify-center text-2xl flex-shrink-0 ${
                r.unlocked ? 'bg-[#C5A059]/20 text-[#C5A059]' : 'bg-white/5 text-white/30'
              }`}>{r.icon}</div>
              <div className="flex-1">
                <div className={`font-medium text-sm ${r.unlocked ? 'text-white' : 'text-white/50'}`}>{r.title}</div>
                <div className="text-white/40 text-xs mt-0.5">{r.desc}</div>
              </div>
              <div className="text-right">
                <div className={`text-sm font-bold ${r.unlocked ? 'text-[#C5A059]' : 'text-white/20'}`}>+{r.xp}</div>
                <div className="text-white/30 text-[10px] uppercase">XP</div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* All Tiers */}
      {tab === 'tiers' && (
        <div className="space-y-4">
          {TIERS.map((tier, i) => (
            <div key={tier.name} className={`p-6 border transition-all ${
              tier.name === currentTier.name ? 'border-[#C5A059]/40 bg-[#C5A059]/5' : 'border-white/5 bg-[#0E0E0E]'
            }`}>
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-4">
                  <div className={`text-3xl ${tier.color}`}>{tier.icon}</div>
                  <div>
                    <div className={`font-serif text-xl font-light ${tier.color}`}>{tier.name}</div>
                    <div className="text-white/30 text-xs">
                      {tier.max === Infinity ? `${tier.min.toLocaleString()}+ XP` : `${tier.min.toLocaleString()} – ${tier.max.toLocaleString()} XP`}
                    </div>
                  </div>
                </div>
                {tier.name === currentTier.name && (
                  <div className="bg-[#C5A059] text-black text-[10px] uppercase tracking-[0.2em] px-3 py-1 font-bold">Current</div>
                )}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                {(PERKS[tier.name] || []).map((perk, j) => (
                  <div key={j} className="flex items-center gap-2 text-sm text-white/50">
                    <span className={tier.color}>✓</span> {perk}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
